export enum DocumentType {
  PAN = 'PAN',
  Aadhaar = 'Aadhaar',
  GST = 'GST',
  AddressProof = 'AddressProof',
  Deed = 'Deed',
  LetterFromPartners = 'LetterFromPartners',
  ListOfDirectorsPartnersMembersTrustee = 'ListOfDirectorsPartnersMembersTrustee',
  COI = 'COI',
  MOA = 'MOA',
  AOA = 'AOA',
  BoardResolution = 'BoardResolution',
  CertificateOfCommencement = 'CertificateOfCommencement',
  BankAccountProof = 'BankAccountProof',
  RegistrationCertificate = 'RegistrationCertificate',
  DarpanRegistration = 'DarpanRegistration',
  RBILicense = 'RBILicense',
  RecentPhotograph = 'RecentPhotograph',
  SignatureWithStamp = 'SignatureWithStamp',
  OfficeInsidePhoto = 'OfficeInsidePhoto',
  OfficeOutsidePhoto = 'OfficeOutsidePhoto',
  SignatoryPAN = 'SignatoryPAN',
  DirectorPAN = 'DirectorPAN',
  AadhaarCardOrDrivingLicenseOrPassportOrVoterId = 'AadhaarCardOrDrivingLicenseOrPassportOrVoterId',
  AdditionalDocument1 = 'AdditionalDocument1',
  AdditionalDocument2 = 'AdditionalDocument2',
}
